import {
  FiAlertCircle,
  FiArrowRight,
  FiArrowUp,
  FiAward,
  FiBook,
  FiBriefcase,
  FiCheck,
  FiCheckCircle,
  FiCloud,
  FiCode,
  FiCoffee,
  FiCpu,
  FiDatabase,
  FiDownload,
  FiExternalLink,
  FiFacebook,
  FiGithub,
  FiGlobe,
  FiHeart,
  FiInstagram,
  FiLayers,
  FiLayout,
  FiLoader,
  FiMail,
  FiMapPin,
  FiMenu,
  FiMonitor,
  FiPhone,
  FiSend,
  FiStar,
  FiTarget,
  FiTerminal,
  FiTool,
  FiUser,
  FiX,
  FiZap,
} from 'react-icons/fi'
import {
  SiCloudflare,
  SiC,
  SiCplusplus,
  SiCss,
  SiDocker,
  SiExpress,
  SiFirebase,
  SiGit,
  SiHtml5,
  SiJavascript,
  SiJupyter,
  SiLinux,
  SiMongodb,
  SiMysql,
  SiNodedotjs,
  SiOpenjdk,
  SiPandas,
  SiPostgresql,
  SiPython,
  SiPytorch,
  SiReact,
  SiScikitlearn,
  SiTailwindcss,
  SiTensorflow,
  SiTypescript,
  SiVercel,
  SiVite,
} from 'react-icons/si'

/**
 * Central icon registry. Every data file references icons by these keys,
 * so swapping a technology icon is a one-line change here.
 * Unknown keys fall back to a neutral code icon (never crashes the page).
 */
export const iconRegistry = {
  // UI
  code: FiCode,
  layout: FiLayout,
  database: FiDatabase,
  cpu: FiCpu,
  cloud: FiCloud,
  monitor: FiMonitor,
  terminal: FiTerminal,
  tool: FiTool,
  layers: FiLayers,
  user: FiUser,
  briefcase: FiBriefcase,
  book: FiBook,
  award: FiAward,
  coffee: FiCoffee,
  zap: FiZap,
  check: FiCheck,
  star: FiStar,
  heart: FiHeart,
  globe: FiGlobe,
  target: FiTarget,
  mail: FiMail,
  phone: FiPhone,
  location: FiMapPin,
  download: FiDownload,
  send: FiSend,
  loader: FiLoader,
  menu: FiMenu,
  close: FiX,
  arrowRight: FiArrowRight,
  arrowUp: FiArrowUp,
  external: FiExternalLink,
  success: FiCheckCircle,
  error: FiAlertCircle,
  github: FiGithub,
  facebook: FiFacebook,
  instagram: FiInstagram,

  // Technologies
  javascript: SiJavascript,
  typescript: SiTypescript,
  python: SiPython,
  c: SiC,
  cplusplus: SiCplusplus,
  java: SiOpenjdk,
  html5: SiHtml5,
  css3: SiCss,
  react: SiReact,
  tailwindcss: SiTailwindcss,
  vite: SiVite,
  nodejs: SiNodedotjs,
  express: SiExpress,
  mongodb: SiMongodb,
  postgresql: SiPostgresql,
  mysql: SiMysql,
  firebase: SiFirebase,
  tensorflow: SiTensorflow,
  pytorch: SiPytorch,
  scikitlearn: SiScikitlearn,
  pandas: SiPandas,
  jupyter: SiJupyter,
  docker: SiDocker,
  git: SiGit,
  linux: SiLinux,
  cloudflare: SiCloudflare,
  vercel: SiVercel,
}

export const getIcon = (key) => iconRegistry[key] ?? FiCode

export const iconColors = {
  javascript: '#F7DF1E',
  typescript: '#3178C6',
  python: '#3776AB',
  c: '#A8B9CC',
  cplusplus: '#00599C',
  java: '#ED8B00',
  react: '#61DAFB',
  tailwindcss: '#06B6D4',
  html5: '#E34F26',
  css3: '#1572B6',
  vite: '#646CFF',
  nodejs: '#339933',
  mongodb: '#47A248',
  postgresql: '#4169E1',
  mysql: '#4479A1',
  express: '#000000',
  firebase: '#FFCA28',
  tensorflow: '#FF6F00',
  pytorch: '#EE4C2C',
  scikitlearn: '#F7931E',
  pandas: '#150458',
  jupyter: '#F37626',
  docker: '#2496ED',
  git: '#F05032',
  github: '#181717',
  linux: '#FCC624',
  cloudflare: '#F38020',
  vercel: '#000000',
}

export const getIconColor = (key) => iconColors[key] ?? 'currentColor'
